"""Scaffolder: problem statement -> docs/PROJECT_SPEC.md + docs/BUILD_PLAN.md.

Calls the same generate_spec() as POST /api/intake (no duplicated logic).
Works in mock mode with no key. Writes ONLY the two docs; refuses to
overwrite without --force. Never touches app code.

Usage (from repo root):
  python backend/scripts/scaffold.py "Paste problem statement here"
  python backend/scripts/scaffold.py --file problem.txt [--force]
"""
import argparse
import asyncio
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "backend"))

SPEC_PATH = os.path.join(ROOT, "docs", "PROJECT_SPEC.md")
PLAN_PATH = os.path.join(ROOT, "docs", "BUILD_PLAN.md")


def render_spec_md(spec, fallback: str) -> str:
    lines = [
        f"# {spec.title}",
        "",
        f"_Generated by intake ({fallback} mode). Edit freely._",
        "",
        f"**Target user:** {spec.target_user}",
        "",
        f"**Core problem:** {spec.core_problem}",
        "",
        "## Must-have features (exactly 3, all demoable)",
        "",
    ]
    for i, f in enumerate(spec.must_have_features, 1):
        lines.append(f"{i}. **{f.name}** — {f.description}")
    lines += ["", "## Stretch goals", ""]
    lines += [f"- {g}" for g in spec.stretch_goals] or ["- (none)"]
    lines += ["", "## Demo flow", ""]
    lines += [f"{i}. {s}" for i, s in enumerate(spec.demo_flow, 1)]
    lines += ["", "## Judging criteria map", ""]
    lines += [f"- **{k}:** {v}" for k, v in spec.judging_criteria_map.items()] or ["- (none)"]
    lines += ["", f"## Suggested kit tools: {', '.join(spec.suggested_tools) or '(none)'}", ""]
    lines += ["## Risks", ""]
    lines += [f"- {r}" for r in spec.risks] or ["- (none)"]
    return "\n".join(lines) + "\n"


BUILD_PLAN_TEMPLATE = """# Build plan for: {title}

_Checklist order for a 24-hour hackathon. File paths are where to edit in this kit._

- [ ] **Setup (30 min):** copy `backend/.env.example` -> `backend/.env`, run `python scripts/preflight.py`, start backend (`cd backend && uvicorn app.main:app --port 8000`) + frontend (`cd frontend && npm install && npm run dev`)
- [ ] **Feature 1 — {f1} (`frontend/src/pages/Home.jsx`, `backend/app/api/routes_solve.py`):** {f1d}
- [ ] **Feature 2 — {f2} (`backend/app/agents/tools.py` + one `elif` rule in `backend/app/agents/nodes.py`, see `scripts/new_feature.md`):** {f2d}
- [ ] **Feature 3 — {f3} (`backend/app/api/routes_upload.py` + `frontend/src/components/SourcePanel.jsx`):** {f3d}
- [ ] **Demo prep (45 min):** rehearse `docs/demo-plan.md` 3-min script, record backup video
- [ ] **README (15 min):** update `README.md` problem section + `docs/api-contract.md` if endpoints changed
- [ ] **Pitch (30 min):** fill `docs/presentation-outline.md` (10 slides), tailor to judging criteria above
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Scaffold PROJECT_SPEC.md + BUILD_PLAN.md from a problem statement")
    ap.add_argument("problem", nargs="?", help="Problem statement text")
    ap.add_argument("--file", help="Read problem statement from file")
    ap.add_argument("--force", action="store_true", help="Overwrite existing docs")
    args = ap.parse_args()

    if args.file:
        with open(args.file, encoding="utf-8") as f:
            problem = f.read().strip()
    else:
        problem = (args.problem or "").strip()
    if not problem:
        print("error: provide a problem statement argument or --file", file=sys.stderr)
        return 2
    if len(problem) > 8000:
        print("error: problem too long (max 8000 chars)", file=sys.stderr)
        return 2
    for path in (SPEC_PATH, PLAN_PATH):
        if os.path.exists(path) and not args.force:
            print(f"error: {path} exists (use --force to overwrite)", file=sys.stderr)
            return 1

    from app.api.routes_intake import generate_spec
    spec, fallback, reason = asyncio.run(generate_spec(problem))
    f = spec.must_have_features
    with open(SPEC_PATH, "w", encoding="utf-8") as fh:
        fh.write(render_spec_md(spec, fallback))
    with open(PLAN_PATH, "w", encoding="utf-8") as fh:
        fh.write(BUILD_PLAN_TEMPLATE.format(
            title=spec.title, f1=f[0].name, f1d=f[0].description,
            f2=f[1].name, f2d=f[1].description, f3=f[2].name, f3d=f[2].description))
    print(f"wrote {SPEC_PATH} + {PLAN_PATH} ({fallback} mode, reason={reason})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
